name: Clean and Convert
on: push
jobs:
  clean-and-convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run cleanjsonify
      - run: npm run geojsonify
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.0.0
        with:
          commit_author_email: pogohwh@gmail.com
          commit_author_name: PoGOHWH
          commit_message: Automatically cleaned and converted data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
